# Generated by Django 5.0.2 on 2024-05-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phone_num', models.IntegerField(max_length=12)),
                ('status', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=400)),
                ('phone_num', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('F_name', models.CharField(max_length=40)),
                ('M_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=400)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phone_num', models.IntegerField(max_length=12)),
                ('subject', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=552, null=True)),
            ],
        ),
    ]
