# Generated by Django 5.0.2 on 2024-05-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='phone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='phone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher_account',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
