# Generated by Django 5.0.2 on 2024-05-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_status_phone_num_alter_status_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status',
            new_name='student_status',
        ),
    ]
