# Generated by Django 5.0.2 on 2024-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_status_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_status',
            name='status',
            field=models.CharField(),
        ),
    ]
