# Generated by Django 5.0.2 on 2024-05-23 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_student_status_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='created',
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='updated',
        ),
        migrations.AddField(
            model_name='student_status',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 10, 34, 31, 555958, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_info',
            name='phone_num',
            field=models.IntegerField(max_length=20),
        ),
    ]
