# Generated by Django 5.0.2 on 2024-05-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_student_info_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='phone_num',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student_status',
            name='phone_num',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher_account',
            name='phone_num',
            field=models.IntegerField(max_length=15),
        ),
    ]
