# Generated by Django 5.0.2 on 2024-05-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_student_info_phone_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='phone_num',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student_status',
            name='phone_num',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher_account',
            name='phone_num',
            field=models.BigIntegerField(),
        ),
    ]
