# Generated by Django 5.0.2 on 2024-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_student_info_phone_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=400)),
                ('phone_num', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('f_name', models.CharField(max_length=40)),
                ('m_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phone_num', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('status_date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='teacher_account',
            new_name='TeacherAccount',
        ),
        migrations.DeleteModel(
            name='student_info',
        ),
        migrations.DeleteModel(
            name='student_status',
        ),
    ]
