# Generated by Django 5.0.2 on 2024-05-23 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_studentinfo_studentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='password',
            field=models.CharField(default=datetime.datetime(2024, 5, 23, 17, 31, 25, 953509, tzinfo=datetime.timezone.utc), max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
