# Generated by Django 5.0.2 on 2024-05-23 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_studentinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 5, 23, 17, 48, 33, 626920, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
