# Generated by Django 5.0.2 on 2024-05-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_studentinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
