# Generated by Django 5.0.2 on 2024-05-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='m_name',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='subject',
        ),
    ]
