# Generated by Django 5.0.2 on 2024-05-31 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_studentinfo_address_remove_studentinfo_f_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheraccount',
            name='password',
            field=models.CharField(default=datetime.datetime(2024, 5, 31, 14, 26, 31, 317033, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
