# Generated by Django 5.0.2 on 2024-05-31 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_teacheraccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheraccount',
            name='username',
            field=models.CharField(default=datetime.datetime(2024, 5, 31, 14, 32, 33, 649574, tzinfo=datetime.timezone.utc), max_length=40),
            preserve_default=False,
        ),
    ]
