# Generated by Django 5.0.2 on 2024-05-31 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_teacheraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='subject',
            field=models.CharField(default=datetime.datetime(2024, 5, 31, 15, 12, 19, 321076, tzinfo=datetime.timezone.utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacheraccount',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 5, 31, 15, 12, 23, 120225, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
