# Generated by Django 5.0.2 on 2024-05-31 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_studentinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='subject',
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('subject', models.CharField(max_length=40)),
                ('student_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.studentinfo')),
            ],
        ),
    ]
