# Generated by Django 5.0.2 on 2024-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_studentinfo_image_remove_studentinfo_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='subject',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
